# Generated by Django 5.2.4 on 2025-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('audio_input', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_output', models.CharField(blank=True, max_length=255, null=True)),
                ('is_CHATGPT', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
